language: java
script: ./gradlew clean build

sudo: false

jdk:
  - oraclejdk8

env:
  global:
    - secure: "GzBGoVG/LPAl0IS4PZWyG7PHmiN7qXhnhj+qBgKg5cv5fG94NqS66Fboh6p3PRhGG8LF1RijMvxVrazFNM2iQOFOln6jZlI2PmEngwjzWd5P1yn47t4GantuGgj7P2Asj+qLm68zs/BHuR0yZ9o+TgvvzeQRaI18CS4wf5SOFA0A2NrIDnETAvc5BMS7KnbJdT9rjoaj0TpAz0odZgmstbv0HmIdmYPH6asw33yR7PaTk7YAzl9Xw00kl2QFwUm+0zbeN3l8eD5y5sd/lYacwKpINQBqDYMoPhzCO11eW2kvfu1BNAdH3HiVtfTSTg0IejoPF+qDoOMh39gqihIXnQiJtg+lzAIprKRP56IeCiVJ0VdLzD1XffIobUffeo/RNYD6FCswRk0H0Zsk/JYy5WjUnRPLQ01oVFS2HCiOKXYeCIlMNTFbQhTWZ/vq0ACyCC3HWOadU6rlTpeW6yZyQBbAzi2Yro0m4RjuY93MtTCEGr8zm+/Sfzs+ylRebOQdPEiIZhCvds4if65AoAnJenRTpgaab45F+zl8x4mglmYAIpSJukI7gpF5GyKsyR5BoiMSyhlSxSx/7HOD8NQjevtcOCGjuh3DFvMydXuPaAr7W9zLdT7Hk5HcS+Acrn2SREyZJuzzq647Bbsq4iiZI6yQX2PM9T4YHSIftpfCGKo="
    - secure: "K6f/sL+xo4JBocAoXsDuc/VcmXr4p3z8BbC9OideEgZ95Ti3N+hxhcXMIgrHG+obu3CDbykh+RTWHHncg7iMzTyRghQbH4yh0ZeltLlcPRBcaKFCsoqQVYYVMEzEmbllk5+nQQQSxLfb/SeBVMADshJCXhwpT5Oin8lEn6U4TflJ7w7sibyG0KIeVH/4zeyjjWA1gI6aUtqK4tdMQuz2WZRA4ZIPVPQnyjW7J+rKLutMprQYqhCoEQKzepv59S2EQ2mAV8Y8xH+n6jbrVbl5SNLozKVv+xd2hdGxIzRYSJLo/801dgSUCI77kQ13OkZjcIzux+Ylt4pxJ9QMcpzewRX0kk7Mv1o85PdBTd6cBUna9sykTbL1MC9sBI4jBrJvHa9cjzkjkumtt8tQdRaeVyl8wy2IOkMKhiLV/yAL/MLP42hGqmyxcdFp/B/LrqdgMhV4fmbHvuuR5jIdEi9G00fkGbdJw9oKJwDUvOFHW5J5XarXp4qBd0w4+RdLbtUKyRH2XWGaO6K8T9HnAd0GZrpazi9BJxCAfiK4M/tIuVphjGbUXYACEMtRFbU8QvNT+JsmGZZJgTke6t6Q8rT1UJBBgjNU2S7rJGWLjORmCHNxdTgV2zoIfBxJDzxz8e/k/l+ZiJ/ybglbBNDOQ21DzrhAF7FSYDGO5bt/8zdTuVw="

before_install:
  - openssl aes-256-cbc -pass pass:$SONATYPE_PASS -in deploy/secring.gpg.enc -out deploy/secring.gpg -d
  - openssl aes-256-cbc -pass pass:$SONATYPE_PASS -in deploy/pubring.gpg.enc -out deploy/pubring.gpg -d
  - mkdir -p ~/.gradle
  - openssl aes-256-cbc -pass pass:$SONATYPE_PASS -in deploy/gradle.properties.enc -out ~/.gradle/gradle.properties -d